// Code generated by tools/grammar-gen — DO NOT EDIT.
//
// Source: docs/grammar/sap-server-name.yaml (version 1)
// Regenerate via: go run ./tools/grammar-gen
//
// This parser is regex-free per CLAUDE.md "Regex Discipline (MANDATORY)":
// only string-prefix checks and char-code range comparisons are used.
package sapname

import "strings"

// Kind enumerates the SAP server kinds. The bare string (e.g. "vsp",
// "sap-gui") is the on-the-wire identifier — keep these stable across
// regenerations because callers compare against them.
const (
	KindVSP    = "vsp"
	KindSAPGUI = "sap-gui"
)

const (
	sidLen    = 3
	clientLen = 3
	separator = "-"
)

// Parsed is the output of ParseServerName. When ok=false from
// ParseServerName, Parsed is the zero value and must not be inspected.
type Parsed struct {
	Kind   string
	SID    string
	Client string // empty when not present in the name
}

// ParseServerName splits a server name into its grammar components.
// Returns (zero-value, false) for any input that does not match the
// grammar — including non-SAP names, malformed SIDs, malformed clients,
// and partial/truncated inputs.
//
// Grammar (from docs/grammar/sap-server-name.yaml):
//
//	vsp-<SID>(-<Client>)?
//	sap-gui-<SID>(-<Client>)?
//	SID    = 3 chars from A-Z, 0-9
//	Client = 3 chars from 0-9
func ParseServerName(name string) (Parsed, bool) {
	var kind, rest string
	switch {
	case strings.HasPrefix(name, "sap-gui-"):
		kind = "sap-gui"
		rest = name[8:]
	case strings.HasPrefix(name, "vsp-"):
		kind = "vsp"
		rest = name[4:]
	default:
		return Parsed{}, false
	}

	if len(rest) < sidLen {
		return Parsed{}, false
	}
	sid := rest[:sidLen]
	if !isValidSID(sid) {
		return Parsed{}, false
	}
	rest = rest[sidLen:]

	if len(rest) == 0 {
		return Parsed{Kind: kind, SID: sid}, true
	}
	if !strings.HasPrefix(rest, separator) {
		return Parsed{}, false
	}
	rest = rest[len(separator):]
	if len(rest) != clientLen {
		return Parsed{}, false
	}
	if !isValidClient(rest) {
		return Parsed{}, false
	}
	return Parsed{Kind: kind, SID: sid, Client: rest}, true
}

// isValidSID returns true when s contains exactly sidLen chars, each in
// the configured SID charset.
func isValidSID(s string) bool {
	if len(s) != sidLen {
		return false
	}
	for i := 0; i < len(s); i++ {
		c := s[i]
		if !((c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9')) {
			return false
		}
	}
	return true
}

// isValidClient returns true when s contains exactly clientLen chars,
// each in the configured client charset.
func isValidClient(s string) bool {
	if len(s) != clientLen {
		return false
	}
	for i := 0; i < len(s); i++ {
		c := s[i]
		if !(c >= '0' && c <= '9') {
			return false
		}
	}
	return true
}

// IsVSP reports whether name is a vsp server name.
func IsVSP(name string) bool {
	p, ok := ParseServerName(name)
	return ok && p.Kind == KindVSP
}

// IsSAPGUI reports whether name is a sap-gui server name.
func IsSAPGUI(name string) bool {
	p, ok := ParseServerName(name)
	return ok && p.Kind == KindSAPGUI
}

// IsSAP reports whether name is any SAP server name (any configured
// kind). Equivalent to ParseServerName(name) succeeding.
func IsSAP(name string) bool {
	_, ok := ParseServerName(name)
	return ok
}
