package main

import (
	"errors"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/spf13/cobra"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// Phase 7 — tests for `mcp-ctl doctor` (B-16). Strategy mirrors
// install_claude_code_test.go: fakeRunner injects `claude` calls,
// httptest.Server fakes the gateway, and a temp dir backs the
// extensions root via $GATEWAY_VSCODE_EXTENSIONS_DIR.

// doctorTestEnv composes all the moving pieces a single doctor.run()
// invocation needs. Returned doctor is wired with the temp extensions
// dir (no patched index.js by default — tests that need the patched
// branch call writePatchedIndexJS).
type doctorTestEnv struct {
	t            *testing.T
	gateway      *httptest.Server
	tokenPath    string
	tokenContent string
	extDir       string
	runner       *fakeRunner
	cmd          *cobra.Command
	doctor       *doctor
}

// makeDoctorTestEnv builds the standard happy-path environment.
//   - gateway: GET /api/v1/health -> 200
//   - token file: 32 chars
//   - extDir: empty (no patch); call writePatchedIndexJS(env, "1.18.0")
//     to add the marker file in the same dir.
//   - runner: claude --version succeeds; plugin list returns mcp-gateway
func makeDoctorTestEnv(t *testing.T) *doctorTestEnv {
	t.Helper()

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/api/v1/health":
			w.WriteHeader(http.StatusOK)
			fmt.Fprint(w, `{"status":"ok"}`)
		default:
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	t.Cleanup(srv.Close)

	tmpDir := t.TempDir()
	tokenPath := filepath.Join(tmpDir, "auth.token")
	const tok = "doctor-test-token-12345678901234"
	require.NoError(t, os.WriteFile(tokenPath, []byte(tok+"\n"), 0o600))

	extDir := filepath.Join(tmpDir, "extensions")
	require.NoError(t, os.MkdirAll(extDir, 0o755))

	fr := newFakeRunner()
	fr.respond("claude --version", &fakeCommand{stdout: []byte("Claude Code 2.1.123\n")})
	fr.respond("claude plugin list --json", &fakeCommand{
		stdout: []byte(`{"plugins":[{"name":"mcp-gateway","user_config":{"auth_token":"x"}}]}`),
	})

	cmd := newDoctorCmd()
	cmd.Flags().String("api-url", srv.URL, "")
	cmd.Flags().String("auth-token-file", tokenPath, "")

	doc := &doctor{
		runner:        fr.run,
		httpClient:    &http.Client{Timeout: 1 * time.Second},
		extensionsDir: extDir,
	}

	return &doctorTestEnv{
		t:            t,
		gateway:      srv,
		tokenPath:    tokenPath,
		tokenContent: tok,
		extDir:       extDir,
		runner:       fr,
		cmd:          cmd,
		doctor:       doc,
	}
}

// writePatchedIndexJS plants a patched anthropic.claude-code-X.Y.Z
// extension under env.extDir so checkPatchApplied finds the marker.
func writePatchedIndexJS(t *testing.T, env *doctorTestEnv, version string) {
	t.Helper()
	dir := filepath.Join(env.extDir, "anthropic.claude-code-"+version, "webview")
	require.NoError(t, os.MkdirAll(dir, 0o755))
	body := "// MCP Gateway Patch v" + version + " — autogenerated by apply-mcp-gateway.sh\n" +
		"console.log('hello world');\n"
	require.NoError(t, os.WriteFile(filepath.Join(dir, "index.js"), []byte(body), 0o644))
}

// resultByName finds a check by its name; fails the test when absent.
func resultByName(t *testing.T, results []checkResult, name string) checkResult {
	t.Helper()
	for _, r := range results {
		if r.name == name {
			return r
		}
	}
	t.Fatalf("no check named %q in results", name)
	return checkResult{}
}

// --- happy path ---

func TestDoctor_AllChecksPassWhenEnvironmentIsHealthy(t *testing.T) {
	env := makeDoctorTestEnv(t)
	writePatchedIndexJS(t, env, "1.18.0")

	results := env.doctor.run(env.cmd)
	require.Len(t, results, 5)

	for _, r := range results {
		assert.Equal(t, checkPass, r.status, "check %q should pass: detail=%s hint=%s", r.name, r.detail, r.hint)
	}
	assert.False(t, anyFailed(results))
}

// --- gateway down ---

func TestDoctor_GatewayUnreachable(t *testing.T) {
	env := makeDoctorTestEnv(t)
	env.gateway.Close() // tear down so /health connection is refused

	results := env.doctor.run(env.cmd)
	r := resultByName(t, results, "gateway reachable")
	assert.Equal(t, checkFail, r.status)
	assert.Contains(t, r.hint, "mcp-ctl daemon start")
}

func TestDoctor_GatewayReturns401(t *testing.T) {
	env := makeDoctorTestEnv(t)
	env.gateway.Close()
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusUnauthorized)
	}))
	t.Cleanup(srv.Close)
	require.NoError(t, env.cmd.Flags().Set("api-url", srv.URL))

	results := env.doctor.run(env.cmd)
	r := resultByName(t, results, "gateway reachable")
	assert.Equal(t, checkFail, r.status)
	assert.Contains(t, r.hint, "--refresh-token")
}

// --- auth token failures ---

func TestDoctor_AuthTokenFileMissing(t *testing.T) {
	env := makeDoctorTestEnv(t)
	require.NoError(t, os.Remove(env.tokenPath))

	results := env.doctor.run(env.cmd)
	r := resultByName(t, results, "auth token")
	assert.Equal(t, checkFail, r.status)
	assert.Contains(t, r.detail, env.tokenPath)
}

func TestDoctor_AuthTokenFileEmpty(t *testing.T) {
	env := makeDoctorTestEnv(t)
	require.NoError(t, os.WriteFile(env.tokenPath, []byte("   \n\t\n"), 0o600))

	results := env.doctor.run(env.cmd)
	r := resultByName(t, results, "auth token")
	assert.Equal(t, checkFail, r.status)
	assert.Contains(t, r.detail, "is empty")
}

// --- claude CLI failures ---

func TestDoctor_ClaudeCLIMissing_FailsCheckAndSkipsPluginList(t *testing.T) {
	env := makeDoctorTestEnv(t)
	env.runner.respond("claude --version", &fakeCommand{err: errors.New("exec: claude: not found")})
	env.runner.respond("claude plugin list --json", &fakeCommand{err: errors.New("exec: claude: not found")})

	results := env.doctor.run(env.cmd)
	cli := resultByName(t, results, "claude CLI")
	assert.Equal(t, checkFail, cli.status)
	assert.Contains(t, cli.hint, "claude.com/claude-code")

	plugin := resultByName(t, results, "plugin installed")
	assert.Equal(t, checkSkip, plugin.status, "plugin check should SKIP, not FAIL, when CLI absent")
}

// --- plugin not installed ---

func TestDoctor_PluginNotInListed(t *testing.T) {
	env := makeDoctorTestEnv(t)
	env.runner.respond("claude plugin list --json", &fakeCommand{stdout: []byte(`{"plugins":[]}`)})

	results := env.doctor.run(env.cmd)
	r := resultByName(t, results, "plugin installed")
	assert.Equal(t, checkFail, r.status)
	assert.Contains(t, r.hint, "install-claude-code")
}

func TestDoctor_PluginListMalformedJSON(t *testing.T) {
	env := makeDoctorTestEnv(t)
	env.runner.respond("claude plugin list --json", &fakeCommand{stdout: []byte(`{not json`)})

	results := env.doctor.run(env.cmd)
	r := resultByName(t, results, "plugin installed")
	assert.Equal(t, checkFail, r.status)
	assert.Contains(t, r.detail, "could not parse")
}

// --- patch failures ---

func TestDoctor_PatchMissing_NoExtensionDir(t *testing.T) {
	env := makeDoctorTestEnv(t)
	// extDir exists but contains no anthropic.claude-code-* subdirs.

	results := env.doctor.run(env.cmd)
	r := resultByName(t, results, "webview patch")
	assert.Equal(t, checkFail, r.status)
	assert.Contains(t, r.detail, "no anthropic.claude-code-* dir")
}

func TestDoctor_PatchMissing_ExtPresentButIndexJSUnpatched(t *testing.T) {
	env := makeDoctorTestEnv(t)
	dir := filepath.Join(env.extDir, "anthropic.claude-code-1.18.0", "webview")
	require.NoError(t, os.MkdirAll(dir, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "index.js"), []byte("// stock claude code, no marker\n"), 0o644))

	results := env.doctor.run(env.cmd)
	r := resultByName(t, results, "webview patch")
	assert.Equal(t, checkFail, r.status)
	assert.Contains(t, r.detail, "no patched index.js")
}

func TestDoctor_PatchPresent_PicksLatestVersionWhenMultiple(t *testing.T) {
	env := makeDoctorTestEnv(t)
	// Two extension versions: only the older one carries the marker.
	// Reverse alphabetical scan still finds it (because we iterate all).
	older := filepath.Join(env.extDir, "anthropic.claude-code-1.17.0", "webview")
	newer := filepath.Join(env.extDir, "anthropic.claude-code-1.18.0", "webview")
	require.NoError(t, os.MkdirAll(older, 0o755))
	require.NoError(t, os.MkdirAll(newer, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(older, "index.js"),
		[]byte("// MCP Gateway Patch v1.17.0\n"), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(newer, "index.js"),
		[]byte("// stock\n"), 0o644))

	results := env.doctor.run(env.cmd)
	r := resultByName(t, results, "webview patch")
	assert.Equal(t, checkPass, r.status)
	assert.Contains(t, r.detail, "1.17.0")
}

// --- exit-code wiring + table render ---

func TestDoctor_ExecuteCommand_ExitsZeroWhenAllPass(t *testing.T) {
	env := makeDoctorTestEnv(t)
	writePatchedIndexJS(t, env, "1.18.0")

	t.Setenv("GATEWAY_VSCODE_EXTENSIONS_DIR", env.extDir)
	out, err := executeCommand(env.gateway, "--auth-token-file", env.tokenPath, "doctor", "--no-color")
	// We can't substitute the doctor's commandRunner via executeCommand (it
	// uses realCommand), so we expect either:
	//   - exit 0 if the dev box has claude CLI + the plugin + the patched ext, OR
	//   - exit 1 with hints listed.
	// What we DO assert is that the table renders all 5 check rows and
	// that no Go panic / cobra usage error leaks out.
	if err != nil {
		var iee *installExitError
		require.True(t, errors.As(err, &iee), "non-installExitError leaked: %v", err)
		assert.Equal(t, installExitUsage, iee.Code)
	}
	for _, want := range []string{"gateway reachable", "auth token", "claude CLI", "plugin installed", "webview patch"} {
		assert.Contains(t, out, want, "doctor table should list %q", want)
	}
}

// --- isSemverByte / readPatchVersion edge cases ---

func TestReadPatchVersion_ParsesMarkerInBundle(t *testing.T) {
	dir := t.TempDir()
	indexJS := filepath.Join(dir, "index.js")
	body := strings.Repeat("/*pad*/", 100) + "// MCP Gateway Patch v1.16.0\n" +
		strings.Repeat("zzz", 200)
	require.NoError(t, os.WriteFile(indexJS, []byte(body), 0o644))

	ver, ok := readPatchVersion(indexJS)
	assert.True(t, ok)
	assert.Equal(t, "v1.16.0", ver)
}

func TestReadPatchVersion_MissingFileReturnsFalse(t *testing.T) {
	_, ok := readPatchVersion(filepath.Join(t.TempDir(), "absent.js"))
	assert.False(t, ok)
}

func TestReadPatchVersion_MarkerBeyondHeadCutoff(t *testing.T) {
	dir := t.TempDir()
	indexJS := filepath.Join(dir, "index.js")
	// Push the marker past 4 KiB on purpose — readPatchVersion only
	// scans the head, so this must NOT match.
	body := strings.Repeat("a", 5000) + "// MCP Gateway Patch v9.9.9\n"
	require.NoError(t, os.WriteFile(indexJS, []byte(body), 0o644))

	_, ok := readPatchVersion(indexJS)
	assert.False(t, ok)
}

func TestIsSemverByte(t *testing.T) {
	for _, b := range []byte{'0', '5', '9', '.'} {
		assert.True(t, isSemverByte(b), "byte %q should be semver", b)
	}
	for _, b := range []byte{'a', 'Z', '-', ' ', '\n', 'v'} {
		assert.False(t, isSemverByte(b), "byte %q should not be semver", b)
	}
}

// --- formatting / status symbols ---

func TestCheckStatusSymbol_HonorsNoColor(t *testing.T) {
	plain := checkPass.symbol(true)
	assert.Equal(t, "PASS", plain)
	assert.NotContains(t, plain, "\033[", "no-color must strip ANSI")

	colored := checkPass.symbol(false)
	assert.Contains(t, colored, "PASS")
	assert.Contains(t, colored, "\033[", "color mode must include ANSI")
}

// TestRenderResults_FailedCheckIncludesHintAndSummary locks the
// rendered table so a future format tweak does not silently drop the
// remediation hints — the entire purpose of the doctor table is to
// give operators a one-screen punch list.
func TestRenderResults_FailedCheckIncludesHintAndSummary(t *testing.T) {
	results := []checkResult{
		{name: "gateway reachable", status: checkPass, detail: "ok"},
		{name: "auth token", status: checkFail, detail: "missing", hint: "run install-claude-code"},
		{name: "claude CLI", status: checkSkip, detail: "blocked", hint: "see above"},
	}
	var out strings.Builder
	renderResults(&out, results, true /*noColor*/)
	rendered := out.String()
	assert.Contains(t, rendered, "PASS")
	assert.Contains(t, rendered, "FAIL")
	assert.Contains(t, rendered, "SKIP")
	assert.Contains(t, rendered, "hint: run install-claude-code")
	assert.Contains(t, rendered, "hint: see above")
	assert.Contains(t, rendered, "One or more checks failed")
}

func TestCompareSemver_OrdersNumericallyNotLexically(t *testing.T) {
	// The bug this guards: lexicographic compare puts "1.10.0" BEFORE
	// "1.9.0", which would make checkPatchApplied report the older
	// version when both extension dirs are patched.
	cases := []struct {
		a, b string
		want int
	}{
		{"v1.18.0", "v1.17.0", 1},
		{"v1.17.0", "v1.18.0", -1},
		{"v1.10.0", "v1.9.0", 1},   // numeric order beats lex
		{"v1.9.0", "v1.10.0", -1},  // ditto
		{"v1.18.0", "v1.18.0", 0},
		{"v1.18", "v1.18.0", 0},    // missing components default to 0
		{"1.18.0", "v1.18.0", 0},   // 'v' prefix tolerated
		{"v2.0.0", "v1.99.99", 1},  // major dominates
	}
	for _, tc := range cases {
		got := compareSemver(tc.a, tc.b)
		assert.Equal(t, tc.want, got, "compareSemver(%q, %q)", tc.a, tc.b)
	}
}

func TestCheckPatchApplied_PicksHighestSemverWhenMultiplePatched(t *testing.T) {
	env := makeDoctorTestEnv(t)
	// Both 1.9.0 (older) and 1.10.0 (newer) carry markers. Lex order
	// says 1.10.0 < 1.9.0 because '0' < '9'; numeric order says 1.10.0
	// > 1.9.0. The detail line must report 1.10.0.
	for _, ver := range []string{"1.9.0", "1.10.0"} {
		dir := filepath.Join(env.extDir, "anthropic.claude-code-"+ver, "webview")
		require.NoError(t, os.MkdirAll(dir, 0o755))
		body := "// MCP Gateway Patch v" + ver + " — autogenerated\n"
		require.NoError(t, os.WriteFile(filepath.Join(dir, "index.js"), []byte(body), 0o644))
	}

	results := env.doctor.run(env.cmd)
	r := resultByName(t, results, "webview patch")
	assert.Equal(t, checkPass, r.status)
	assert.Contains(t, r.detail, "v1.10.0", "must pick highest semver, not lex-first")
	assert.NotContains(t, r.detail, "v1.9.0)", "must NOT report the older version")
}

func TestIsTerminal_FalseForBuffer(t *testing.T) {
	// strings.Builder is not *os.File — must report non-terminal.
	var b strings.Builder
	assert.False(t, isTerminal(&b))
}

func TestRenderResults_AllPassPrintsSuccessSummary(t *testing.T) {
	results := []checkResult{
		{name: "gateway reachable", status: checkPass, detail: "ok"},
		{name: "auth token", status: checkPass, detail: "ok"},
	}
	var out strings.Builder
	renderResults(&out, results, true)
	rendered := out.String()
	assert.Contains(t, rendered, "All checks passed")
	assert.NotContains(t, rendered, "hint:", "passing checks must not emit hint lines")
}
