// Code generated by tools/grammar-gen — DO NOT EDIT.
//
// Source: docs/grammar/sap-server-name.yaml (version 1)
// Regenerate via: go run ./tools/grammar-gen
//
// This parser is regex-free per CLAUDE.md "Regex Discipline (MANDATORY)":
// only string-prefix checks and char-code range comparisons are used.

/**
 * SAP server kinds (on-the-wire identifiers — keep stable across regenerations).
 */
export const KIND_VSP = 'vsp';
export const KIND_SAP_GUI = 'sap-gui';

/** Union type of all SAP server kinds. */
export type SapKind = 'vsp' | 'sap-gui';

/**
 * Parsed result of {@link parseServerName}. `client` is the empty string
 * when the optional client suffix is absent; consumers can branch on
 * `client === ''` (or `parsed.client.length === 0`) to detect this.
 */
export interface ParsedServerName {
	kind: SapKind;
	sid: string;
	client: string;
}

const SID_LEN = 3;
const CLIENT_LEN = 3;
const SEPARATOR = '-';

/**
 * Parse a server name into its grammar components. Returns null for any
 * input that does not match the grammar — including non-SAP names,
 * malformed SIDs, malformed clients, and partial/truncated inputs.
 */
export function parseServerName(name: string): ParsedServerName | null {
	let kind: SapKind;
	let rest: string;
	if (name.startsWith('sap-gui-')) {
		kind = 'sap-gui';
		rest = name.substring(8);
	} else if (name.startsWith('vsp-')) {
		kind = 'vsp';
		rest = name.substring(4);
	} else {
		return null;
	}

	if (rest.length < SID_LEN) {
		return null;
	}
	const sid = rest.substring(0, SID_LEN);
	if (!isValidSID(sid)) {
		return null;
	}
	rest = rest.substring(SID_LEN);

	if (rest.length === 0) {
		return { kind, sid, client: '' };
	}
	if (!rest.startsWith(SEPARATOR)) {
		return null;
	}
	rest = rest.substring(SEPARATOR.length);
	if (rest.length !== CLIENT_LEN) {
		return null;
	}
	if (!isValidClient(rest)) {
		return null;
	}
	return { kind, sid, client: rest };
}

function isValidSID(s: string): boolean {
	if (s.length !== SID_LEN) {
		return false;
	}
	for (let i = 0; i < s.length; i++) {
		const c = s.charCodeAt(i);
		if (!((c >= 65 && c <= 90) || (c >= 48 && c <= 57))) {
			return false;
		}
	}
	return true;
}

function isValidClient(s: string): boolean {
	if (s.length !== CLIENT_LEN) {
		return false;
	}
	for (let i = 0; i < s.length; i++) {
		const c = s.charCodeAt(i);
		if (!((c >= 48 && c <= 57))) {
			return false;
		}
	}
	return true;
}

/** Returns true when name is a vsp server name. */
export function isVSP(name: string): boolean {
	const p = parseServerName(name);
	return p !== null && p.kind === 'vsp';
}

/** Returns true when name is a sap-gui server name. */
export function isSAPGUI(name: string): boolean {
	const p = parseServerName(name);
	return p !== null && p.kind === 'sap-gui';
}

/** Returns true when name is any SAP server name (any configured kind). */
export function isSAP(name: string): boolean {
	return parseServerName(name) !== null;
}
