import * as vscode from 'vscode';
import * as fs from 'node:fs';
import * as path from 'node:path';
import {
	loadCommandsCatalog,
	loadServersCatalog,
	type CommandEntry,
	type ServerEntry,
} from './catalog';
import { resolveCatalogDir } from './catalog-path';
import type { ServerDataCache, CacheRefreshPayload } from './server-data-cache';
import type { ServerView } from './types';
import { SERVER_NAME_RE } from './validation';
import { logger } from './logger';

// Phase 16.9 T16.9.3 — disclaimer lines sit BELOW the MARKER but above
// all body content. Operators (and Claude) periodically confuse
// `.claude/commands/*.md` (prompt templates) with MCP server registrations.
// Plain-text reminders inline with every generated file close that gap.
export const DISCLAIMER_LINE_2 = '<!-- NOTE: This is a slash-command prompt template, NOT an MCP server registration. -->';
export const DISCLAIMER_LINE_3 = '<!-- MCP servers are registered via the mcp-gateway plugin (see README §Connecting Claude Code). -->';

const MARKER = '<!-- AUTO-GENERATED by mcp-gateway extension. DO NOT EDIT \u2014 will be overwritten. -->';

// HEADER bundles MARKER + 2 disclaimer lines. Always emitted as the first
// three lines of every generated file. Keep MARKER on line 1 for
// isOwnedFile() gating (regression test slash-command-generator.test.ts).
const HEADER = MARKER + '\n' + DISCLAIMER_LINE_2 + '\n' + DISCLAIMER_LINE_3;

// CC.2 allow-list. Any `${var}` token NOT in this map is left literal in the
// output per CC.2 (plan/PLAN-catalogs.md) — no recursive substitution, no
// silent eval, and no risk that a rogue catalog author turns a template into
// a secret exfiltration channel via a novel variable name.
const KNOWN_VARS = ['server_name', 'server_url'] as const;

export class SlashCommandGenerator implements vscode.Disposable {
	private readonly cache: ServerDataCache;
	private readonly extensionUri: vscode.Uri | undefined;
	private previousStatus = new Map<string, string>();
	private lastTask: Promise<void> = Promise.resolve();
	private loggedUnmarkedFiles = new Set<string>();
	private seeded = false;
	private subscription: vscode.Disposable | undefined;
	private configSubscription: vscode.Disposable | undefined;
	private disposed = false;

	// CC.1 catalog cache. Loaded lazily on the first generateCommand call after
	// enable() or after invalidateCatalogCache(). Both catalogs load together so
	// ${server_url} substitution (CC.2) can cross-reference the server entry.
	private catalogLoaded = false;
	private commandEntries: CommandEntry[] = [];
	private serverEntries: ServerEntry[] = [];

	constructor(cache: ServerDataCache, extensionUri?: vscode.Uri) {
		this.cache = cache;
		this.extensionUri = extensionUri;
	}

	enable(): void {
		if (this.subscription) { return; }
		this.subscription = this.cache.onDidRefresh((payload) => {
			this.onCacheRefresh(payload);
		});
		// CC.1: catalog reload when the operator override moves. Matches the
		// `vscode.workspace.onDidChangeConfiguration` pattern used in
		// sap-tree-provider.ts:27 and extension.ts:178 — keep this subscription
		// live for the generator's lifetime so the next transition after a
		// config change picks up the new catalog directory.
		if (!this.configSubscription) {
			this.configSubscription = vscode.workspace.onDidChangeConfiguration((e) => {
				if (!e.affectsConfiguration('mcpGateway.catalogPath')) { return; }
				this.invalidateCatalogCache();
			});
		}
	}

	disable(): void {
		this.subscription?.dispose();
		this.subscription = undefined;
		this.configSubscription?.dispose();
		this.configSubscription = undefined;
		this.seeded = false;
		this.previousStatus.clear();
		this.loggedUnmarkedFiles.clear();
		this.invalidateCatalogCache();
	}

	dispose(): void {
		this.disposed = true;
		this.disable();
	}

	/**
	 * Drop the cached catalog entries so the next transition reloads from disk.
	 * Invoked by the config watcher (CC.1) and from disable()/tests.
	 */
	invalidateCatalogCache(): void {
		this.catalogLoaded = false;
		this.commandEntries = [];
		this.serverEntries = [];
	}

	resolveCommandsDir(): string | null {
		const config = vscode.workspace.getConfiguration('mcpGateway');
		const raw = config.get<string>('slashCommandsPath', '${workspaceFolder}/.claude/commands');

		if (raw.includes('${workspaceFolder}')) {
			const folders = vscode.workspace.workspaceFolders;
			if (!folders || folders.length === 0) { return null; }
			return raw.replace('${workspaceFolder}', folders[0].uri.fsPath);
		}

		return raw;
	}

	private onCacheRefresh(payload: CacheRefreshPayload): void {
		if (this.disposed) { return; }

		const dir = this.resolveCommandsDir();
		if (!dir) { return; }

		const servers = payload.servers;

		if (!this.seeded) {
			for (const s of servers) {
				this.previousStatus.set(s.name, s.status);
			}
			this.seeded = true;
			return;
		}

		if (payload.lastRefreshFailed) { return; }

		const currentNames = new Set<string>();
		for (const s of servers) {
			currentNames.add(s.name);
			const prev = this.previousStatus.get(s.name);
			const curr = s.status;

			if (prev !== curr) {
				if (curr === 'running' || curr === 'degraded') {
					this.enqueue(() => this.generateCommand(dir, s));
				} else if (curr === 'stopped' || curr === 'disabled') {
					this.enqueue(() => this.deleteCommand(dir, s.name));
				}
			}
			this.previousStatus.set(s.name, curr);
		}

		// Orphan cleanup: servers removed from the list.
		for (const [name] of this.previousStatus) {
			if (!currentNames.has(name)) {
				this.enqueue(() => this.deleteCommand(dir, name));
				this.previousStatus.delete(name);
			}
		}

		// Orphan cleanup: stale .md files in the directory.
		if (!payload.lastRefreshFailed) {
			this.enqueue(() => this.cleanOrphans(dir, currentNames));
		}
	}

	private enqueue(task: () => Promise<void>): void {
		this.lastTask = this.lastTask.then(task).catch((err: unknown) => {
			logger.error('slash-command-generator', 'Queued task failed', err);
		});
	}

	private async generateCommand(dir: string, server: ServerView): Promise<void> {
		// SERVER_NAME_RE is /^[a-zA-Z0-9][a-zA-Z0-9_-]{0,63}$/ — rejects any
		// character that could introduce a path component (no '/', '\\', '.',
		// ':' — see validation.ts). path.join below is therefore guaranteed to
		// land inside `dir`; no traversal vector from daemon-supplied names.
		if (!SERVER_NAME_RE.test(server.name)) { return; }
		const filePath = path.join(dir, `${server.name}.md`);
		const owned = await this.isOwnedFile(filePath);
		if (!owned) { return; }

		const content = await this.buildContent(server);
		// AUDIT B-NEW-26 (Phase 10): atomic write via tmp+rename.
		// Plain `fs.promises.writeFile` is non-atomic — Node writes incrementally
		// then fsyncs. A VS Code crash or power loss mid-write can leave a
		// truncated `.md` file whose first line is cut off, which then fails
		// `isOwnedFile()` (the MARKER on line 1 is no longer present). Result:
		// the partial file becomes a permanent orphan in `~/.claude/commands/`
		// that we never overwrite. Fix: write to `${filePath}.tmp`, then
		// atomically rename. POSIX guarantees atomic rename; on Windows,
		// `fs.promises.rename` is atomic when source and dest are on the same
		// volume (always true here — both under `dir`).
		const tmpPath = `${filePath}.tmp`;
		try {
			await fs.promises.mkdir(dir, { recursive: true });
			await fs.promises.writeFile(tmpPath, content, 'utf8');
			await fs.promises.rename(tmpPath, filePath);
		} catch {
			// Log failure without throwing — queued writes must not break the
			// chain. Best-effort cleanup of the tmp file so we do not leave a
			// `.md.tmp` orphan if rename failed mid-flight (cleanOrphans also
			// scrubs these on next refresh).
			try { await fs.promises.unlink(tmpPath); } catch { /* ENOENT etc. */ }
		}
	}

	private async deleteCommand(dir: string, name: string): Promise<void> {
		if (!SERVER_NAME_RE.test(name)) { return; }
		const filePath = path.join(dir, `${name}.md`);
		const owned = await this.isOwnedFile(filePath);
		if (!owned) { return; }

		try {
			await fs.promises.unlink(filePath);
		} catch (err: unknown) {
			if ((err as NodeJS.ErrnoException).code === 'ENOENT') { return; }
		}
	}

	private async cleanOrphans(dir: string, currentNames: Set<string>): Promise<void> {
		let files: string[];
		try {
			files = await fs.promises.readdir(dir);
		} catch {
			return;
		}

		for (const file of files) {
			// AUDIT B-NEW-26 (Phase 10): scrub `.md.tmp` orphans left by a
			// crashed atomic-write. They cannot be valid generator output and
			// will only confuse subsequent runs. Deleted unconditionally.
			if (file.endsWith('.md.tmp')) {
				try { await fs.promises.unlink(path.join(dir, file)); } catch { /* best-effort */ }
				continue;
			}
			if (!file.endsWith('.md')) { continue; }
			const name = file.slice(0, -3);
			if (currentNames.has(name)) { continue; }
			await this.deleteCommand(dir, name);
		}
	}

	private async isOwnedFile(filePath: string): Promise<boolean> {
		try {
			const content = await fs.promises.readFile(filePath, 'utf8');
			const firstLine = content.split('\n')[0];
			if (firstLine === MARKER) { return true; }
			if (!this.loggedUnmarkedFiles.has(filePath)) {
				this.loggedUnmarkedFiles.add(filePath);
			}
			return false;
		} catch (err: unknown) {
			if ((err as NodeJS.ErrnoException).code === 'ENOENT') { return true; }
			return false;
		}
	}

	/**
	 * CC.1: best-effort one-shot load of both catalogs. Missing catalog files,
	 * loader warnings, and no-entry lookups all fall through to the skeleton
	 * builder so a broken catalog never breaks slash-command generation.
	 *
	 * Both catalogs load together because ${server_url} substitution (CC.2)
	 * needs the ServerEntry url keyed by server_name — loading commands alone
	 * would force a second roundtrip on every transition.
	 */
	private async ensureCatalogLoaded(): Promise<void> {
		// Note (A-1, v1.5.0 finalization audit): `catalogLoaded = true` is set
		// before the awaited load to keep behaviour idempotent inside the .then-
		// serialized enqueue() chain (each enqueued task awaits the previous).
		// A Promise-sentinel refinement is tracked as a v1.6 candidate.
		if (this.catalogLoaded) { return; }
		this.catalogLoaded = true;
		const dir = await resolveCatalogDir(this.extensionUri);
		if (!dir) {
			// No usable catalog directory — skeleton fallback for every transition.
			return;
		}
		try {
			const [servers, commands] = await Promise.all([
				loadServersCatalog(path.join(dir, 'servers.json')),
				loadCommandsCatalog(path.join(dir, 'commands.json')),
			]);
			this.serverEntries = servers.entries;
			this.commandEntries = commands.entries;
		} catch {
			// loader contracts (see catalog.ts) promise no throw — this catch is
			// defensive only and leaves the cache empty so we fall through to the
			// skeleton builder on the next lookup.
		}
	}

	private findCommandEntry(serverName: string): CommandEntry | null {
		for (const entry of this.commandEntries) {
			if (entry.server_name === serverName) { return entry; }
		}
		return null;
	}

	private findServerEntry(serverName: string): ServerEntry | null {
		for (const entry of this.serverEntries) {
			if (entry.name === serverName) { return entry; }
		}
		return null;
	}

	/**
	 * CC.2: allow-list variable substitution. ONLY `${server_name}` and
	 * `${server_url}` are replaced; every other `${var}` token survives
	 * verbatim. Uses `String.prototype.replaceAll` with string needles, which
	 * does plain substring replacement (no regex interpretation) so catalog
	 * authors cannot slip a crafted token through a regex shortcut.
	 */
	private substituteVariables(body: string, serverName: string, serverUrl: string): string {
		// Values-by-name map so future allow-list additions only touch one place.
		const values: Record<(typeof KNOWN_VARS)[number], string> = {
			server_name: serverName,
			server_url: serverUrl,
		};
		let out = body;
		for (const name of KNOWN_VARS) {
			out = out.replaceAll(`\${${name}}`, values[name]);
		}
		return out;
	}

	private async buildContent(server: ServerView): Promise<string> {
		await this.ensureCatalogLoaded();
		const cmdEntry = this.findCommandEntry(server.name);
		if (!cmdEntry) {
			// CC.1: no catalog entry for this server — emit the pre-CC skeleton
			// verbatim. This preserves the regression test at
			// slash-command-generator.test.ts:120-131.
			return this.skeletonTemplate(server);
		}
		const srvEntry = this.findServerEntry(server.name);
		const url = typeof srvEntry?.url === 'string' ? srvEntry.url : '';
		const body = this.substituteVariables(cmdEntry.template_md, server.name, url);
		// CC.3: marker stays on line 1 so isOwnedFile() still gates overwrite
		// and delete. Catalog content sits BELOW the marker, exactly as the
		// skeleton does. Operator edits BELOW line 1 are silently overwritten
		// on the next regeneration — documented known limitation (D3, README).
		return `${HEADER}\n${body}`;
	}

	private skeletonTemplate(server: ServerView): string {
		const tools = server.tools ?? [];
		const toolsList = tools.length > 0
			? tools.map((t) => `- ${t.name}`).join('\n')
			: '- _(no tools exposed)_';

		return [
			MARKER,
			DISCLAIMER_LINE_2,
			DISCLAIMER_LINE_3,
			`# ${server.name}`,
			'',
			`**Status:** ${server.status}`,
			`**Transport:** ${server.transport}`,
			'',
			'## Tools',
			'',
			toolsList,
			'',
			'## Invocation',
			'',
			`This server is managed by mcp-gateway. Use the MCP Gateway extension to interact with \`${server.name}\`.`,
			'',
		].join('\n');
	}
}

export { MARKER };
