import * as vscode from 'vscode';
import * as fs from 'node:fs';
import * as path from 'node:path';
import type { ServerDataCache, CacheRefreshPayload } from './server-data-cache';
import type { ServerView } from './types';
import { SERVER_NAME_RE } from './validation';

const MARKER = '<!-- AUTO-GENERATED by mcp-gateway extension. DO NOT EDIT \u2014 will be overwritten. -->';

export class SlashCommandGenerator implements vscode.Disposable {
	private readonly cache: ServerDataCache;
	private previousStatus = new Map<string, string>();
	private lastTask: Promise<void> = Promise.resolve();
	private loggedUnmarkedFiles = new Set<string>();
	private seeded = false;
	private subscription: vscode.Disposable | undefined;
	private disposed = false;

	constructor(cache: ServerDataCache) {
		this.cache = cache;
	}

	enable(): void {
		if (this.subscription) { return; }
		this.subscription = this.cache.onDidRefresh((payload) => {
			this.onCacheRefresh(payload);
		});
	}

	disable(): void {
		this.subscription?.dispose();
		this.subscription = undefined;
		this.seeded = false;
		this.previousStatus.clear();
		this.loggedUnmarkedFiles.clear();
	}

	dispose(): void {
		this.disposed = true;
		this.disable();
	}

	resolveCommandsDir(): string | null {
		const config = vscode.workspace.getConfiguration('mcpGateway');
		const raw = config.get<string>('slashCommandsPath', '${workspaceFolder}/.claude/commands');

		if (raw.includes('${workspaceFolder}')) {
			const folders = vscode.workspace.workspaceFolders;
			if (!folders || folders.length === 0) { return null; }
			return raw.replace('${workspaceFolder}', folders[0].uri.fsPath);
		}

		return raw;
	}

	private onCacheRefresh(payload: CacheRefreshPayload): void {
		if (this.disposed) { return; }

		const dir = this.resolveCommandsDir();
		if (!dir) { return; }

		const servers = payload.servers;

		if (!this.seeded) {
			for (const s of servers) {
				this.previousStatus.set(s.name, s.status);
			}
			this.seeded = true;
			return;
		}

		if (payload.lastRefreshFailed) { return; }

		const currentNames = new Set<string>();
		for (const s of servers) {
			currentNames.add(s.name);
			const prev = this.previousStatus.get(s.name);
			const curr = s.status;

			if (prev !== curr) {
				if (curr === 'running' || curr === 'degraded') {
					this.enqueue(() => this.generateCommand(dir, s));
				} else if (curr === 'stopped' || curr === 'disabled') {
					this.enqueue(() => this.deleteCommand(dir, s.name));
				}
			}
			this.previousStatus.set(s.name, curr);
		}

		// Orphan cleanup: servers removed from the list.
		for (const [name] of this.previousStatus) {
			if (!currentNames.has(name)) {
				this.enqueue(() => this.deleteCommand(dir, name));
				this.previousStatus.delete(name);
			}
		}

		// Orphan cleanup: stale .md files in the directory.
		if (!payload.lastRefreshFailed) {
			this.enqueue(() => this.cleanOrphans(dir, currentNames));
		}
	}

	private enqueue(task: () => Promise<void>): void {
		this.lastTask = this.lastTask.then(task).catch(() => {});
	}

	private async generateCommand(dir: string, server: ServerView): Promise<void> {
		if (!SERVER_NAME_RE.test(server.name)) { return; }
		const filePath = path.join(dir, `${server.name}.md`);
		const owned = await this.isOwnedFile(filePath);
		if (!owned) { return; }

		const content = this.contentTemplate(server);
		try {
			await fs.promises.mkdir(dir, { recursive: true });
			await fs.promises.writeFile(filePath, content, 'utf8');
		} catch {
			// Log failure without throwing — queued writes must not break the chain.
		}
	}

	private async deleteCommand(dir: string, name: string): Promise<void> {
		if (!SERVER_NAME_RE.test(name)) { return; }
		const filePath = path.join(dir, `${name}.md`);
		const owned = await this.isOwnedFile(filePath);
		if (!owned) { return; }

		try {
			await fs.promises.unlink(filePath);
		} catch (err: unknown) {
			if ((err as NodeJS.ErrnoException).code === 'ENOENT') { return; }
		}
	}

	private async cleanOrphans(dir: string, currentNames: Set<string>): Promise<void> {
		let files: string[];
		try {
			files = await fs.promises.readdir(dir);
		} catch {
			return;
		}

		for (const file of files) {
			if (!file.endsWith('.md')) { continue; }
			const name = file.slice(0, -3);
			if (currentNames.has(name)) { continue; }
			await this.deleteCommand(dir, name);
		}
	}

	private async isOwnedFile(filePath: string): Promise<boolean> {
		try {
			const content = await fs.promises.readFile(filePath, 'utf8');
			const firstLine = content.split('\n')[0];
			if (firstLine === MARKER) { return true; }
			if (!this.loggedUnmarkedFiles.has(filePath)) {
				this.loggedUnmarkedFiles.add(filePath);
			}
			return false;
		} catch (err: unknown) {
			if ((err as NodeJS.ErrnoException).code === 'ENOENT') { return true; }
			return false;
		}
	}

	private contentTemplate(server: ServerView): string {
		const tools = server.tools ?? [];
		const toolsList = tools.length > 0
			? tools.map((t) => `- ${t.name}`).join('\n')
			: '- _(no tools exposed)_';

		return [
			MARKER,
			`# ${server.name}`,
			'',
			`**Status:** ${server.status}`,
			`**Transport:** ${server.transport}`,
			'',
			'## Tools',
			'',
			toolsList,
			'',
			'## Invocation',
			'',
			`This server is managed by mcp-gateway. Use the MCP Gateway extension to interact with \`${server.name}\`.`,
			'',
		].join('\n');
	}
}

export { MARKER };
